debug=true
logging.level.root=WARN
logging.level.org.springframework.data.rest=ERROR
logging.level.se.uu.ebc.luntan=DEBUG
#debug:true
logging.file.path=/tmp/luntan
#
spring.jackson.default-property-inclusion=non_empty
#
server.display-name=Luntan
#
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
spring.persistence.exceptiontranslation.enabled=true
#
management.endpoints.web.exposure.include=*
#
spring.jpa.hibernate.ddl-auto=update
#
ldap.urls=ldaps://akka-ldap.uu.se:636
ldap.partitionSuffix=
ldap.principal=uid=@ldap.uid@,ou=Ldapclient,dc=uu,dc=se
ldap.password=@ldap.password@
#
spring.profiles.active=@spring.profiles.active@
